import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import { getServerSession } from "next-auth";
import SessionProvider from "@/components/SessionProvider";
import Logo from "@/components/Logo";
import LoginButton from "@/components/LoginButton";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <SessionProvider session={session}>
          <header className=" px-6 py-3 flex justify-between">
            <Logo />
            <LoginButton />
          </header>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
