import type { Metadata } from "next";
import "../globals.css";

import Sidebar from "@/components/sidebar/Sidebar";

import DashboardHeader from "@/components/DashboardHeader";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <DashboardHeader />
      <div className="grid h-[calc(100vh-60px)] w-full lg:grid-cols-[280px_1fr]">
        <Sidebar />
        {children}
      </div>
    </>
  );
}
